# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agtid', models.IntegerField(max_length=2)),
                ('agname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=200)),
                ('apercentage', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agid', models.IntegerField(max_length=10)),
                ('agpercentage', models.IntegerField(max_length=3)),
                ('agtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AgType')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(max_length=10)),
                ('cname', models.CharField(max_length=8)),
                ('term', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='agid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AssessmentGroup'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='agtid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AgType'),
        ),
    ]
