# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170318_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cid',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='agtype',
            name='agtid',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='agtid',
        ),
        migrations.RemoveField(
            model_name='assessmentgroup',
            name='agid',
        ),
        migrations.AddField(
            model_name='assessment',
            name='duedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=200),
        ),
    ]
